In [1]:
from dataclasses import dataclass

import numpy as np

In [2]:
@dataclass(frozen=True)
class Quaternion:
    x: float
    y: float
    z: float
    s: float

In [3]:
def get_rotation_matrix(q: Quaternion) -> np.ndarray:
    return np.array(
        [[q.x ** 2 - q.y ** 2 - q.z ** 2 + q.s ** 2, 2 * (q.x * q.y + q.z * q.s), 2 * (q.x * q.z - q.y * q.s)],
         [2 * (q.x * q.y - q.z * q.s), -q.x ** 2 + q.y ** 2 - q.z ** 2 + q.s ** 2, 2 * (q.y * q.z + q.x * q.s)],
         [2 * (q.x * q.z + q.y * q.s), 2 * (q.y * q.z - q.x * q.s), -q.x ** 2 - q.y ** 2 + q.z ** 2 + q.s ** 2]]
    )

In [4]:
q = Quaternion(-0.9336623549461364746, 0.02849436365067958832, -0.1522108763456344604, -0.3229468762874603272)

In [5]:
get_rotation_matrix(q)

array([[ 0.95204   ,  0.04510382,  0.30263146],
       [-0.15152028, -0.78978693,  0.59437238],
       [ 0.2658228 , -0.61172099, -0.74507449]])

In [6]:
example = """
0.952039848 0.045103818 0.302631414
-0.151520260 -0.789786806 0.594372284
0.265822757 -0.611720890 -0.745074369
"""

matrix_aux = np.fromstring(example, sep=' ').reshape(3, 3)

matrix_aux

array([[ 0.95203985,  0.04510382,  0.30263141],
       [-0.15152026, -0.78978681,  0.59437228],
       [ 0.26582276, -0.61172089, -0.74507437]])

In [8]:
matrix_aux2 = np.array([-matrix_aux[1], -matrix_aux[0], -matrix_aux[2]])

matrix_aux2

array([[ 0.15152026,  0.78978681, -0.59437228],
       [-0.95203985, -0.04510382, -0.30263141],
       [-0.26582276,  0.61172089,  0.74507437]])